CREATE DATABASE CURSOFERIAS

--GO

USE CURSOFERIAS

CREATE SCHEMA CFD
CREATE SCHEMA VND

CREATE TABLE CFD.TESTE(
	COD_TESTE INT PRIMARY KEY IDENTITY(1,1),
	TESTE_DESC VARCHAR(30)
)

CREATE TABLE VND.TESTE(
	COD_TESTE INT PRIMARY KEY IDENTITY(1,1),
	TESTE_DESC VARCHAR(30)
)

CREATE TABLE ENDERECOS(
	CODIGO_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
	CEP INT NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	UF CHAR(2) NOT NULL,
)

CREATE TABLE CLIENTES(
	CODIGO_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
	CODIGO_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(CODIGO_ENDERECO) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(15),
	EMAIL VARCHAR(50),
	NUMERO SMALLINT NOT NULL,
	COMPLEMENTO VARCHAR(30)
)

CREATE TABLE VENDAS(
	CODIGO_VENDA INT PRIMARY KEY IDENTITY(1,1),
	CODIGO_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(CODIGO_CLIENTE),
	DATA_VENDA DATETIME NOT NULL,
	SUBTOTAL DECIMAL(10,2) NOT NULL,
	DESCONTO DECIMAL(10,2),
	TOTAL DECIMAL(10,2) NOT NULL,
	ENTREGA CHAR(1)
)

CREATE TABLE PRODUTOS(
	CODIGO_PRODUTO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	PRECO DECIMAL(10,2) NOT NULL,
	ESTOQUE SMALLINT NOT NULL,
)

CREATE TABLE VENDAS_ITENS(
	CODIGO_VENDA INT FOREIGN KEY REFERENCES VENDAS(CODIGO_VENDA) NOT NULL,
	CODIGO_PRODUTO INT FOREIGN KEY REFERENCES PRODUTOS(CODIGO_PRODUTO),
	QUANTIDADE INT NOT NULL
	CONSTRAINT PK_VENDAS_ITENS PRIMARY KEY(CODIGO_VENDA, CODIGO_PRODUTO)
)

CREATE TABLE ENDERECOS_ENTREGA(
	CODIGO_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(CODIGO_ENDERECO),
	CODIGO_VENDA INT FOREIGN KEY REFERENCES VENDAS(CODIGO_VENDA),
	NUMERO SMALLINT NOT NULL,
	COMPLEMENTO VARCHAR(30),
	CONSTRAINT PK_ENDERECOS_ENTREGA PRIMARY KEY(CODIGO_ENDERECO, CODIGO_VENDA)
)